import type User from '@/services/types/UserType'
import type Notification from '@/services/types/NotificationType'
import type Task from '@/services/types/TaskType'

// 模拟用户数据
export const mockUsers: User[] = [
  {
    id: '1',
    firstName: '张',
    lastName: '三',
    email: 'zhangsan@example.com',
    password: 'password123',
    avatar: '/images/user/user-01.jpg',
    bio: '全栈开发工程师',
    phone: '+86 13800138000',
    country: '中国',
    city: '北京',
    state: '北京',
    postalCode: '100000',
    taxId: 'CN123456',
    createdAt: '2023-01-15T08:30:00Z',
    updatedAt: '2023-06-20T14:45:00Z',
    lastLogin: '2023-07-01T09:15:00Z',
    twoFactorEnabled: true,
    role: 'admin',
    status: 'active',
    socialAccounts: {
      google: 'zhangsan@gmail.com',
      twitter: '@zhangsan',
    },
    loginHistory: [
      {
        id: 'h1',
        ipAddress: '192.168.1.1',
        device: 'iPhone 13',
        browser: 'Safari',
        location: '北京, 中国',
        time: '2023-07-01T09:15:00Z',
        status: 'success',
      },
      {
        id: 'h2',
        ipAddress: '192.168.1.2',
        device: 'MacBook Pro',
        browser: 'Chrome',
        location: '上海, 中国',
        time: '2023-06-28T16:30:00Z',
        status: 'success',
      },
    ],
  },
  {
    id: '2',
    firstName: '李',
    lastName: '四',
    email: 'lisi@example.com',
    password: 'password456',
    avatar: '/images/user/user-02.jpg',
    bio: '产品经理',
    phone: '+86 13900139000',
    country: '中国',
    city: '上海',
    state: '上海',
    postalCode: '200000',
    taxId: 'CN654321',
    createdAt: '2023-02-10T10:20:00Z',
    updatedAt: '2023-05-15T11:30:00Z',
    lastLogin: '2023-06-30T14:25:00Z',
    twoFactorEnabled: false,
    role: 'user',
    status: 'active',
    socialAccounts: {
      facebook: 'lisi.facebook',
      linkedin: 'lisi.linkedin',
    },
    loginHistory: [
      {
        id: 'h3',
        ipAddress: '192.168.2.1',
        device: 'Samsung Galaxy S22',
        browser: 'Chrome',
        location: '上海, 中国',
        time: '2023-06-30T14:25:00Z',
        status: 'success',
      },
    ],
  },
  {
    id: '3',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    password: 'password789',
    avatar: '/images/user/user-03.jpg',
    bio: 'Software Engineer',
    phone: '+1 555-123-4567',
    country: 'United States',
    city: 'New York',
    state: 'NY',
    postalCode: '10001',
    taxId: 'US987654',
    createdAt: '2023-03-05T15:40:00Z',
    updatedAt: '2023-06-10T09:50:00Z',
    lastLogin: '2023-06-29T20:10:00Z',
    twoFactorEnabled: true,
    role: 'user',
    status: 'active',
    socialAccounts: {
      google: 'john.doe@gmail.com',
      linkedin: 'john.doe.linkedin',
    },
    loginHistory: [
      {
        id: 'h4',
        ipAddress: '203.0.113.1',
        device: 'Dell XPS',
        browser: 'Firefox',
        location: 'New York, USA',
        time: '2023-06-29T20:10:00Z',
        status: 'success',
      },
    ],
  },
]

// 模拟通知数据
export const mockNotifications: Notification[] = [
  {
    id: 1,
    userName: 'Terry Franci',
    userImage: '/images/user/user-02.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 2,
    userName: 'Terry Franci',
    userImage: '/images/user/user-03.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'offline',
  },
  {
    id: 3,
    userName: 'Terry Franci',
    userImage: '/images/user/user-04.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 4,
    userName: 'Terry Franci',
    userImage: '/images/user/user-05.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 5,
    userName: 'Terry Franci',
    userImage: '/images/user/user-06.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'offline',
  },
  {
    id: 6,
    userName: 'Terry Franci',
    userImage: '/images/user/user-07.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 7,
    userName: 'Terry Franci',
    userImage: '/images/user/user-08.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 8,
    userName: 'Terry Franci',
    userImage: '/images/user/user-09.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
]

// 模拟任务数据
export const mockTasks: Task[] = [
  {
    id: '1',
    name: '完成项目提案',
    description: '为新客户准备项目提案文档，包括项目范围、时间线和预算。',
    status: 'done',
    priority: 'high',
    dueDate: '2023-07-15',
    dueTime: '18:00',
    createdAt: '2023-07-01T10:00:00Z',
    updatedAt: '2023-07-14T16:30:00Z',
    tags: ['提案', '文档', '客户'],
    attachments: [
      {
        id: 'a1',
        name: '项目提案模板.docx',
        url: '/files/project-proposal-template.docx',
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        size: 2500000,
        uploadedAt: '2023-07-01T10:30:00Z',
      },
    ],
    comments: [
      {
        id: 'c1',
        userId: '2', // 李四
        content: '我已经审核了提案，看起来不错！',
        createdAt: '2023-07-10T14:25:00Z',
      },
    ],
    estimatedTime: 8,
    actualTime: 10,
    dependencyIds: [],
    isRecurring: false,
    recurringPattern: null,
    reminderTime: '2023-07-14T09:00:00Z',
  },
  {
    id: '2',
    name: '开发登录页面',
    description: '为新应用程序设计和开发登录页面，包括表单验证和错误处理。',
    status: 'working',
    priority: 'medium',
    dueDate: '2023-07-20',
    dueTime: '09:00',
    createdAt: '2023-07-05T09:15:00Z',
    updatedAt: '2023-07-15T11:20:00Z',
    tags: ['开发', '前端', 'UI'],
    attachments: [],
    comments: [],
    estimatedTime: 6,
    actualTime: 4,
    dependencyIds: [],
    isRecurring: false,
    recurringPattern: null,
    reminderTime: '2023-07-19T09:00:00Z',
  },
  {
    id: '3',
    name: '每周团队会议',
    description: '讨论项目进展、问题和下一步计划。',
    status: 'todo',
    priority: 'medium',
    dueDate: '2023-07-21',
    dueTime: '15:00',
    createdAt: '2023-07-01T08:00:00Z',
    updatedAt: '2023-07-01T08:00:00Z',
    tags: ['会议', '团队'],
    attachments: [],
    comments: [],
    estimatedTime: 1,
    actualTime: null,
    dependencyIds: [],
    isRecurring: true,
    recurringPattern: 'FREQ=WEEKLY;BYDAY=TH;BYHOUR=15;BYMINUTE=0',
    reminderTime: '2023-07-21T14:30:00Z',
  },
  {
    id: '4',
    name: '准备月度报告',
    description: '汇总本月项目进展、财务状况和团队表现。',
    status: 'todo',
    priority: 'high',
    dueDate: '2023-07-31',
    dueTime: '23:59',
    createdAt: '2023-07-10T11:00:00Z',
    updatedAt: '2023-07-10T11:00:00Z',
    tags: ['报告', '财务', '管理'],
    attachments: [],
    comments: [],
    estimatedTime: 4,
    actualTime: null,
    dependencyIds: [],
    isRecurring: true,
    recurringPattern: 'FREQ=MONTHLY;BYMONTHDAY=-1;BYHOUR=23;BYMINUTE=59',
    reminderTime: '2023-07-30T09:00:00Z',
  },
  {
    id: '5',
    name: '更新客户数据库',
    description: '清理和更新客户数据库，确保所有信息都是最新的。',
    status: 'todo',
    priority: 'low',
    dueDate: '2023-07-25T23:59:59Z',
    dueTime: '09:00:00',
    createdAt: '2023-07-16T14:00:00Z',
    updatedAt: '2023-07-16T14:00:00Z',
    tags: ['数据库', '客户', '维护'],
    attachments: [],
    comments: [],
    estimatedTime: 3,
    actualTime: null,
    dependencyIds: [],
    isRecurring: false,
    recurringPattern: null,
    reminderTime: '2023-07-24T09:00:00Z',
  },
]
