import type User from '@/services/types/UserType'
import type Notification from '@/services/types/NotificationType'
import type Task from '@/services/types/TaskType'
import type Habit from '@/services/types/HabitType'

// 模拟用户数据
export const mockUsers: User[] = [
  {
    id: '1',
    firstName: '张',
    lastName: '三',
    email: 'zhangsan@example.com',
    password: 'password123',
    avatar: '/images/user/user-01.jpg',
    bio: '全栈开发工程师',
    phone: '+86 13800138000',
    country: '中国',
    city: '北京',
    state: '北京',
    postalCode: '100000',
    taxId: 'CN123456',
    createdAt: '2023-01-15T08:30:00Z',
    updatedAt: '2023-06-20T14:45:00Z',
    lastLogin: '2023-07-01T09:15:00Z',
    twoFactorEnabled: true,
    role: 'admin',
    status: 'active',
    socialAccounts: {
      google: 'zhangsan@gmail.com',
      twitter: '@zhangsan',
    },
    loginHistory: [
      {
        id: 'h1',
        ipAddress: '192.168.1.1',
        device: 'iPhone 13',
        browser: 'Safari',
        location: '北京, 中国',
        time: '2023-07-01T09:15:00Z',
        status: 'success',
      },
      {
        id: 'h2',
        ipAddress: '192.168.1.2',
        device: 'MacBook Pro',
        browser: 'Chrome',
        location: '上海, 中国',
        time: '2023-06-28T16:30:00Z',
        status: 'success',
      },
    ],
  },
  {
    id: '2',
    firstName: '李',
    lastName: '四',
    email: 'lisi@example.com',
    password: 'password456',
    avatar: '/images/user/user-02.jpg',
    bio: '产品经理',
    phone: '+86 13900139000',
    country: '中国',
    city: '上海',
    state: '上海',
    postalCode: '200000',
    taxId: 'CN654321',
    createdAt: '2023-02-10T10:20:00Z',
    updatedAt: '2023-05-15T11:30:00Z',
    lastLogin: '2023-06-30T14:25:00Z',
    twoFactorEnabled: false,
    role: 'user',
    status: 'active',
    socialAccounts: {
      facebook: 'lisi.facebook',
      linkedin: 'lisi.linkedin',
    },
    loginHistory: [
      {
        id: 'h3',
        ipAddress: '192.168.2.1',
        device: 'Samsung Galaxy S22',
        browser: 'Chrome',
        location: '上海, 中国',
        time: '2023-06-30T14:25:00Z',
        status: 'success',
      },
    ],
  },
  {
    id: '3',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    password: 'password789',
    avatar: '/images/user/user-03.jpg',
    bio: 'Software Engineer',
    phone: '+1 555-123-4567',
    country: 'United States',
    city: 'New York',
    state: 'NY',
    postalCode: '10001',
    taxId: 'US987654',
    createdAt: '2023-03-05T15:40:00Z',
    updatedAt: '2023-06-10T09:50:00Z',
    lastLogin: '2023-06-29T20:10:00Z',
    twoFactorEnabled: true,
    role: 'user',
    status: 'active',
    socialAccounts: {
      google: 'john.doe@gmail.com',
      linkedin: 'john.doe.linkedin',
    },
    loginHistory: [
      {
        id: 'h4',
        ipAddress: '203.0.113.1',
        device: 'Dell XPS',
        browser: 'Firefox',
        location: 'New York, USA',
        time: '2023-06-29T20:10:00Z',
        status: 'success',
      },
    ],
  },
]

// 模拟通知数据
export const mockNotifications: Notification[] = [
  {
    id: 1,
    userName: 'Terry Franci',
    userImage: '/images/user/user-02.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 2,
    userName: 'Terry Franci',
    userImage: '/images/user/user-03.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'offline',
  },
  {
    id: 3,
    userName: 'Terry Franci',
    userImage: '/images/user/user-04.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 4,
    userName: 'Terry Franci',
    userImage: '/images/user/user-05.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 5,
    userName: 'Terry Franci',
    userImage: '/images/user/user-06.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'offline',
  },
  {
    id: 6,
    userName: 'Terry Franci',
    userImage: '/images/user/user-07.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 7,
    userName: 'Terry Franci',
    userImage: '/images/user/user-08.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
  {
    id: 8,
    userName: 'Terry Franci',
    userImage: '/images/user/user-09.jpg',
    action: 'requests permission to change',
    project: 'Project - Nganter App',
    type: 'Project',
    time: '5 min ago',
    status: 'online',
  },
]

// 模拟任务数据
export const mockTasks: Task[] = [
  {
    id: '1',
    name: '完成项目提案',
    description: '为新客户准备项目提案文档，包括项目范围、时间线和预算。',
    status: 'done',
    priority: 'high',
    dueDate: '2023-07-15',
    dueTime: '18:00',
    createdAt: '2023-07-01T10:00:00Z',
    updatedAt: '2023-07-14T16:30:00Z',
    tags: ['提案', '文档', '客户'],
    attachments: [
      {
        id: 'a1',
        name: '项目提案模板.docx',
        url: '/files/project-proposal-template.docx',
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        size: 2500000,
        uploadedAt: '2023-07-01T10:30:00Z',
      },
    ],
    comments: [
      {
        id: 'c1',
        userId: '2', // 李四
        content: '我已经审核了提案，看起来不错！',
        createdAt: '2023-07-10T14:25:00Z',
      },
    ],
    estimatedTime: 8,
    actualTime: 10,
    dependencyIds: [],
    isRecurring: false,
    recurringPattern: null,
    reminderTime: '2023-07-14T09:00:00Z',
  },
  {
    id: '2',
    name: '开发登录页面',
    description: '为新应用程序设计和开发登录页面，包括表单验证和错误处理。',
    status: 'working',
    priority: 'medium',
    dueDate: '2023-07-20',
    dueTime: '09:00',
    createdAt: '2023-07-05T09:15:00Z',
    updatedAt: '2023-07-15T11:20:00Z',
    tags: ['开发', '前端', 'UI'],
    attachments: [],
    comments: [],
    estimatedTime: 6,
    actualTime: 4,
    dependencyIds: [],
    isRecurring: false,
    recurringPattern: null,
    reminderTime: '2023-07-19T09:00:00Z',
  },
  {
    id: '3',
    name: '每周团队会议',
    description: '讨论项目进展、问题和下一步计划。',
    status: 'todo',
    priority: 'medium',
    dueDate: '2023-07-21',
    dueTime: '15:00',
    createdAt: '2023-07-01T08:00:00Z',
    updatedAt: '2023-07-01T08:00:00Z',
    tags: ['会议', '团队'],
    attachments: [],
    comments: [],
    estimatedTime: 1,
    actualTime: null,
    dependencyIds: [],
    isRecurring: true,
    recurringPattern: 'FREQ=WEEKLY;BYDAY=TH;BYHOUR=15;BYMINUTE=0',
    reminderTime: '2023-07-21T14:30:00Z',
  },
  {
    id: '4',
    name: '准备月度报告',
    description: '汇总本月项目进展、财务状况和团队表现。',
    status: 'todo',
    priority: 'high',
    dueDate: '2023-07-31',
    dueTime: '23:59',
    createdAt: '2023-07-10T11:00:00Z',
    updatedAt: '2023-07-10T11:00:00Z',
    tags: ['报告', '财务', '管理'],
    attachments: [],
    comments: [],
    estimatedTime: 4,
    actualTime: null,
    dependencyIds: [],
    isRecurring: true,
    recurringPattern: 'FREQ=MONTHLY;BYMONTHDAY=-1;BYHOUR=23;BYMINUTE=59',
    reminderTime: '2023-07-30T09:00:00Z',
  },
  {
    id: '5',
    name: '更新客户数据库',
    description: '清理和更新客户数据库，确保所有信息都是最新的。',
    status: 'todo',
    priority: 'low',
    dueDate: '2023-07-25T23:59:59Z',
    dueTime: '09:00:00',
    createdAt: '2023-07-16T14:00:00Z',
    updatedAt: '2023-07-16T14:00:00Z',
    tags: ['数据库', '客户', '维护'],
    attachments: [],
    comments: [],
    estimatedTime: 3,
    actualTime: null,
    dependencyIds: [],
    isRecurring: false,
    recurringPattern: null,
    reminderTime: '2023-07-24T09:00:00Z',
  },
]

// 模拟习惯数据
export const mockHabits: Habit[] = [
  {
    id: 'habit-001',
    name: 'Morning Exercise',
    description: '30 minutes of cardio or strength training every morning',
    category: 'health',
    tags: ['fitness', 'morning', 'energy'],
    frequency: {
      type: 'daily',
    },
    startDate: '2024-01-01',
    endDate: null,
    reminderTime: '07:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#FF6B6B',
    icon: '💪',
    cronExpression: '0 0 * * *',
    isArchived: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-06-05T10:30:00Z',
    streakCount: 15,
    longestStreak: 28,
    totalCompletions: 142,
    completionHistory: [
      {
        date: '2025-06-03',
        isCompleted: true,
        note: 'Great morning workout!',
      },
      {
        date: '2025-06-04',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-06-05',
        isCompleted: false,
        note: null,
      },
    ],
    lastCompletedAt: '2025-06-04T07:30:00Z',
  },
  {
    id: 'habit-002',
    name: 'Read 30 Minutes',
    description: 'Read books, articles, or educational content for at least 30 minutes',
    category: 'study',
    tags: ['reading', 'knowledge', 'growth'],
    frequency: {
      type: 'daily',
    },
    startDate: '2024-02-15',
    endDate: null,
    reminderTime: '21:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#4ECDC4',
    icon: '📚',
    cronExpression: '0 0 * * *',
    isArchived: false,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2025-06-05T21:15:00Z',
    streakCount: 7,
    longestStreak: 21,
    totalCompletions: 98,
    completionHistory: [
      {
        date: '2025-06-03',
        isCompleted: true,
        note: 'Finished chapter 5',
      },
      {
        date: '2025-06-04',
        isCompleted: true,
        note: 'Interesting article about AI',
      },
      {
        date: '2025-06-05',
        isCompleted: true,
        note: null,
      },
    ],
    lastCompletedAt: '2025-06-05T21:15:00Z',
  },
  {
    id: 'habit-003',
    name: 'Weekly Planning',
    description: 'Review goals and plan upcoming week every Sunday',
    category: 'creativity',
    tags: ['planning', 'goals', 'organization'],
    frequency: {
      type: 'weekly',
      daysOfWeek: [0],
    },
    startDate: '2024-03-01',
    endDate: null,
    reminderTime: '10:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#45B7D1',
    icon: '📋',
    cronExpression: '0 0 * * 0',
    isArchived: false,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2025-06-01T10:30:00Z',
    streakCount: 3,
    longestStreak: 8,
    totalCompletions: 12,
    completionHistory: [
      {
        date: '2025-05-18',
        isCompleted: true,
        note: 'Planned summer goals',
      },
      {
        date: '2025-05-25',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-06-01',
        isCompleted: true,
        note: 'Set priorities for June',
      },
    ],
    lastCompletedAt: '2025-06-01T10:30:00Z',
  },
  {
    id: 'habit-004',
    name: 'Meditation',
    description: '10-15 minutes of fitness meditation',
    category: 'fitness',
    tags: ['meditation', 'calm', 'focus'],
    frequency: {
      type: 'weekly',
      daysOfWeek: [1, 3, 5],
    },
    startDate: '2024-01-15',
    endDate: null,
    reminderTime: '19:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#9B59B6',
    icon: '🧘',
    cronExpression: '0 0 * * 1,3,5',
    isArchived: false,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2025-06-05T19:15:00Z',
    streakCount: 2,
    longestStreak: 12,
    totalCompletions: 58,
    completionHistory: [
      {
        date: '2025-06-02',
        isCompleted: true,
        note: 'Very relaxing session',
      },
      {
        date: '2025-06-04',
        isCompleted: false,
        note: null,
      },
      {
        date: '2025-06-05',
        isCompleted: true,
        note: null,
      },
    ],
    lastCompletedAt: '2025-06-05T19:15:00Z',
  },
  {
    id: 'habit-005',
    name: 'Save Money',
    description: 'Put aside $50 every month for emergency fund',
    category: 'finance',
    tags: ['saving', 'emergency', 'money'],
    frequency: {
      type: 'monthly',
      daysOfMonth: [1],
    },
    startDate: '2024-01-01',
    endDate: null,
    reminderTime: null,
    reminderType: null,
    reminderLocation: '',
    color: '#F39C12',
    icon: '💰',
    cronExpression: '0 0 1 * *',
    isArchived: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-06-01T00:00:00Z',
    streakCount: 6,
    longestStreak: 6,
    totalCompletions: 6,
    completionHistory: [
      {
        date: '2025-01-01',
        isCompleted: true,
        note: 'Started the year strong',
      },
      {
        date: '2025-02-01',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-03-01',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-04-01',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-05-01',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-06-01',
        isCompleted: true,
        note: 'Emergency fund growing!',
      },
    ],
    lastCompletedAt: '2025-06-01T00:00:00Z',
  },
  {
    id: 'habit-006',
    name: 'Call Family',
    description: 'Weekly call with family members to stay connected',
    category: 'social',
    tags: ['family', 'connection', 'communication'],
    frequency: {
      type: 'weekly',
      daysOfWeek: [6],
    },
    startDate: '2024-04-01',
    endDate: null,
    reminderTime: '15:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#E74C3C',
    icon: '📞',
    cronExpression: '0 0 * * 6',
    isArchived: false,
    createdAt: '2024-04-01T00:00:00Z',
    updatedAt: '2025-05-31T15:30:00Z',
    streakCount: 4,
    longestStreak: 6,
    totalCompletions: 8,
    completionHistory: [
      {
        date: '2025-05-10',
        isCompleted: true,
        note: "Mom's birthday call",
      },
      {
        date: '2025-05-17',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-05-24',
        isCompleted: true,
        note: 'Talked about summer plans',
      },
      {
        date: '2025-05-31',
        isCompleted: true,
        note: null,
      },
    ],
    lastCompletedAt: '2025-05-31T15:30:00Z',
  },
  {
    id: 'habit-007',
    name: 'Language Learning',
    description: 'Practice Spanish for 20 minutes using language app',
    category: 'study',
    tags: ['spanish', 'language', 'duolingo'],
    frequency: {
      type: 'weekly',
      daysOfWeek: [1, 2, 3, 4, 5],
    },
    startDate: '2024-05-01',
    endDate: null,
    reminderTime: '18:30',
    reminderType: 'time',
    reminderLocation: '',
    color: '#27AE60',
    icon: '🗣️',
    cronExpression: '0 0 * * 1,2,3,4,5',
    isArchived: false,
    createdAt: '2024-05-01T00:00:00Z',
    updatedAt: '2025-06-05T18:45:00Z',
    streakCount: 3,
    longestStreak: 14,
    totalCompletions: 45,
    completionHistory: [
      {
        date: '2025-06-03',
        isCompleted: true,
        note: 'Learned new vocabulary',
      },
      {
        date: '2025-06-04',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-06-05',
        isCompleted: true,
        note: 'Grammar lesson completed',
      },
    ],
    lastCompletedAt: '2025-06-05T18:45:00Z',
  },
  {
    id: 'habit-008',
    name: 'Digital Detox',
    description: 'No social media for 2 hours before bedtime',
    category: 'health',
    tags: ['detox', 'sleep', 'mindful'],
    frequency: {
      type: 'daily',
    },
    startDate: '2024-06-01',
    endDate: null,
    reminderTime: '21:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#8E44AD',
    icon: '📵',
    cronExpression: '0 0 * * *',
    isArchived: false,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2025-06-04T23:00:00Z',
    streakCount: 1,
    longestStreak: 9,
    totalCompletions: 28,
    completionHistory: [
      {
        date: '2025-06-03',
        isCompleted: false,
        note: null,
      },
      {
        date: '2025-06-04',
        isCompleted: true,
        note: 'Better sleep quality',
      },
      {
        date: '2025-06-05',
        isCompleted: false,
        note: null,
      },
    ],
    lastCompletedAt: '2025-06-04T23:00:00Z',
  },
  {
    id: 'habit-009',
    name: 'Creative Writing',
    description: 'Write 500 words of creative content or journal entry',
    category: 'creativity',
    tags: ['writing', 'creativity', 'journal'],
    frequency: {
      type: 'weekly',
      daysOfWeek: [0, 2, 4, 6],
    },
    startDate: '2024-03-15',
    endDate: null,
    reminderTime: '20:00',
    reminderType: 'time',
    reminderLocation: '',
    color: '#D35400',
    icon: '✍️',
    cronExpression: '0 0 * * 0,2,4,6',
    isArchived: false,
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2025-06-04T20:30:00Z',
    streakCount: 2,
    longestStreak: 7,
    totalCompletions: 36,
    completionHistory: [
      {
        date: '2025-06-01',
        isCompleted: true,
        note: 'Wrote about weekend adventures',
      },
      {
        date: '2025-06-03',
        isCompleted: false,
        note: null,
      },
      {
        date: '2025-06-04',
        isCompleted: true,
        note: 'Poetry practice today',
      },
    ],
    lastCompletedAt: '2025-06-04T20:30:00Z',
  },
  {
    id: 'habit-010',
    name: 'Drink Water',
    description: 'Drink 8 glasses of water throughout the day',
    category: 'health',
    tags: ['water', 'hydration', 'health'],
    frequency: {
      type: 'daily',
    },
    startDate: '2024-07-01',
    endDate: null,
    reminderTime: null,
    reminderType: null,
    reminderLocation: '',
    color: '#3498DB',
    icon: '💧',
    cronExpression: '0 0 * * *',
    isArchived: true,
    createdAt: '2024-07-01T00:00:00Z',
    updatedAt: '2025-05-15T00:00:00Z',
    streakCount: 0,
    longestStreak: 45,
    totalCompletions: 187,
    completionHistory: [
      {
        date: '2025-05-13',
        isCompleted: true,
        note: null,
      },
      {
        date: '2025-05-14',
        isCompleted: true,
        note: 'Feeling more energetic',
      },
      {
        date: '2025-05-15',
        isCompleted: false,
        note: null,
      },
    ],
    lastCompletedAt: '2025-05-14T18:00:00Z',
  },
]
